language: node_js
sudo: required
notifications:
  email: false
node_js:
- '16'
install:
- npm ci
jobs:
  include:
  - stage: Lint
    script: npm run lint
  - stage: Test
    script: npm run test && npx codecov
env:
  global:
  - REPO="git@github.com:RedHatInsights/acs-ui-build"
  - REPO_DIR="acs-ui-build"
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
