# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: acs
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: acs
    spec:
      feoConfigEnabled: true
      navigationSegments:
        # ACS Navigation is referenced as a foreign module with configuration similar to below
        # TODO: Update this with a link comment to the parent navigation module's repo
        # - segmentref:
        #   frontendname: acs
        #   segmentId: acs
        - segmentId: acs
          navItems:
            - id: acs.nav
              title: Advanced Cluster Security
              expandable: true
              routes:
              - id: clusterOverview
                product: acs
                title: Overview
                href: "/openshift/acs/overview"
                icon: ACSIcon
              - id: acsGettingStarted
                product: acs
                title: Getting Started
                href: "/openshift/acs/getting-started"
              - id: acsInstances
                product: acs
                title: ACS instances
                href: "/openshift/acs/instances"
              - id: clustersDocumentation
                title: Documentation
                isExternal: true
                href: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes
      serviceTiles:
        - section: security
          group: openshift
          id: acs
          href: /openshift/acs/overview
          title: Advanced Cluster Security
          description: Securely build, deploy, and run your cloud applications using Kubernetes-native architecture.
          icon: ACSIcon
      searchEntries:
        - id: acs
          title: Advanced Cluster Security
          description: Securely build, deploy, and run your cloud applications using Kubernetes-native architecture.
          href: /openshift/acs/overview
          alt_title:
            - acs
            - ACS
            - operators
      envName: ${ENV_NAME}
      title: ACS UI
      deploymentRepo: https://github.com/RedHatInsights/acs-ui
      frontend:
        paths:
          - /apps/acs
      API:
        versions:
          - v1
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/acs/fed-mods.json"
        modules:
        - id: "acs"
          module: "./RootApp"
          routes:
            - pathname: /openshift/acs
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/acs-ui

