# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: acs
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: acs
    spec:
      envName: ${ENV_NAME}
      title: ACS UI
      deploymentRepo: https://github.com/RedHatInsights/acs-ui
      frontend:
        paths:
          - /apps/acs
      API:
        versions:
          - v1
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/acs/fed-mods.json"
        modules:
          - id: "acs"
            module: "./RootApp"
            routes:
              - pathname: /application-services/acs
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/acs-ui

