name: Deploy qa-beta
on:
  push:
    branches:
      - main
env:
  TOKEN: ${{ secrets.TOKEN }}
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  SOURCE_REPO: "RedHatInsights/acs-ui"
  SOURCE_BRANCH: main
  DEPLOY_URL: "github.com/RedHatInsights/acs-ui-build"
  WORKSPACE: ${{ github.workspace }}
  GIT_USERNAME: "Actions"
  GIT_EMAIL: "actions@github.com"
jobs:
  deploy-qa-beta:
    if: ${{ false }}  # temporarily disable to see if it breaks the deployment
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      # use the correct node.js version
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # install node dependencies
      - name: Install Dependencies
        run: npm ci
      # run tests
      - name: Test
        run: npm test --passWithNoTests
      # build files
      - name: Build
        run: npm run build:qa:beta --if-present
       # deploy build files to build repo using script
      - name: Checkout RedHatInsights/acs-ui-build repo and push build files from acs-ui
        run: |
          bash ${{ github.workspace }}/.github/scripts/deploy.sh
        env:
          DEPLOY_BRANCH: "qa-beta"
